name: Gradle Build

on:
  pull_request:
    paths:
      - 'src/**'

jobs:

  gradle-build:

    runs-on: ubuntu-latest

    steps:

      # Check-out the repo under $GITHUB_WORKSPACE, so this workflow can access it.
    - name: Checkout repository
      uses: actions/checkout@v2

      # Set up JDK
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

      # Gradle build task
    - name: Invoke gradle task - BUILD
      run: ./gradlew build